// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/shared/proto/v1/billing-provider.proto (package modules.billing.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file modules/shared/proto/v1/billing-provider.proto.
 */
export const file_modules_shared_proto_v1_billing_provider: GenFile = /*@__PURE__*/
  fileDesc("Ci5tb2R1bGVzL3NoYXJlZC9wcm90by92MS9iaWxsaW5nLXByb3ZpZGVyLnByb3RvEhhtb2R1bGVzLmJpbGxpbmcucHJvdG8udjEqUAoPQmlsbGluZ1Byb3ZpZGVyEiAKHEJJTExJTkdfUFJPVklERVJfVU5TUEVDSUZJRUQQABIbChdCSUxMSU5HX1BST1ZJREVSX1NUUklQRRABYgZwcm90bzM");

/**
 * Payment provider a billing entity (customer/product/price/subscription/invoice) belongs to.
 *
 * @generated from enum modules.billing.proto.v1.BillingProvider
 */
export enum BillingProvider {
  /**
   * The provider is not specified.
   *
   * @generated from enum value: BILLING_PROVIDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The provider is Stripe.
   *
   * @generated from enum value: BILLING_PROVIDER_STRIPE = 1;
   */
  STRIPE = 1,
}

/**
 * Payment provider a billing entity (customer/product/price/subscription/invoice) belongs to.
 *
 * @generated from enum modules.billing.proto.v1.BillingProvider
 */
export type BillingProviderJson = "BILLING_PROVIDER_UNSPECIFIED" | "BILLING_PROVIDER_STRIPE";

/**
 * Describes the enum modules.billing.proto.v1.BillingProvider.
 */
export const BillingProviderSchema: GenEnum<BillingProvider, BillingProviderJson> = /*@__PURE__*/
  enumDesc(file_modules_shared_proto_v1_billing_provider, 0);

