// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/shared/proto/v1/placeholder.proto (package modules.shared.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/shared/proto/v1/placeholder.proto.
 */
export const file_modules_shared_proto_v1_placeholder: GenFile = /*@__PURE__*/
  fileDesc("Ciltb2R1bGVzL3NoYXJlZC9wcm90by92MS9wbGFjZWhvbGRlci5wcm90bxIXbW9kdWxlcy5zaGFyZWQucHJvdG8udjEiDQoLUGxhY2Vob2xkZXJiBnByb3RvMw");

/**
 * Placeholder file so buf has a valid module. Replace with real shared types
 * (common wrapper messages, shared enums) as they emerge.
 *
 * @generated from message modules.shared.proto.v1.Placeholder
 */
export type Placeholder = Message<"modules.shared.proto.v1.Placeholder"> & {
};

/**
 * Placeholder file so buf has a valid module. Replace with real shared types
 * (common wrapper messages, shared enums) as they emerge.
 *
 * @generated from message modules.shared.proto.v1.Placeholder
 */
export type PlaceholderJson = {
};

/**
 * Describes the message modules.shared.proto.v1.Placeholder.
 * Use `create(PlaceholderSchema)` to create a new message.
 */
export const PlaceholderSchema: GenMessage<Placeholder, {jsonType: PlaceholderJson}> = /*@__PURE__*/
  messageDesc(file_modules_shared_proto_v1_placeholder, 0);

