// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/dream_board/proto/v1/conversation.proto (package modules.dream_board.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { DreamBoard_DreamBoardStyle, DreamBoard_DreamBoardStyleJson } from "./dream_board_pb";
import { file_modules_dream_board_proto_v1_dream_board } from "./dream_board_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/dream_board/proto/v1/conversation.proto.
 */
export const file_modules_dream_board_proto_v1_conversation: GenFile = /*@__PURE__*/
  fileDesc("Ci9tb2R1bGVzL2RyZWFtX2JvYXJkL3Byb3RvL3YxL2NvbnZlcnNhdGlvbi5wcm90bxIcbW9kdWxlcy5kcmVhbV9ib2FyZC5wcm90by52MSKiCgoMQ29udmVyc2F0aW9uEgoKAmlkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSSwoFc3RhdGUYAyABKA4yPC5tb2R1bGVzLmRyZWFtX2JvYXJkLnByb3RvLnYxLkNvbnZlcnNhdGlvbi5Db252ZXJzYXRpb25TdGF0ZRJECghtZXNzYWdlcxgEIAMoCzIyLm1vZHVsZXMuZHJlYW1fYm9hcmQucHJvdG8udjEuQ29udmVyc2F0aW9uLk1lc3NhZ2USGgoSc2VsZWN0ZWRfZHJlYW1faWRzGAUgAygJElAKDnNlbGVjdGVkX3N0eWxlGAYgASgOMjgubW9kdWxlcy5kcmVhbV9ib2FyZC5wcm90by52MS5EcmVhbUJvYXJkLkRyZWFtQm9hcmRTdHlsZRIVCg1waG90b19za2lwcGVkGAcgASgIEhsKDmRyZWFtX2JvYXJkX2lkGAggASgJSACIAQESDwoHdmVyc2lvbhgJIAEoAxIuCgpjcmVhdGVkX2F0GBQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GBUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI0CgthcmNoaXZlZF9hdBgWIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAYgBARIzCgpkZWxldGVkX2F0GBcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgCiAEBGpYCCgdNZXNzYWdlEkQKBHJvbGUYASABKA4yNi5tb2R1bGVzLmRyZWFtX2JvYXJkLnByb3RvLnYxLkNvbnZlcnNhdGlvbi5NZXNzYWdlUm9sZRILCgNrZXkYAiABKAkSTgoGcGFyYW1zGAMgAygLMj4ubW9kdWxlcy5kcmVhbV9ib2FyZC5wcm90by52MS5Db252ZXJzYXRpb24uTWVzc2FnZS5QYXJhbXNFbnRyeRIMCgR0ZXh0GAQgASgJEisKB3NlbnRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wGi0KC1BhcmFtc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEivgIKEUNvbnZlcnNhdGlvblN0YXRlEiIKHkNPTlZFUlNBVElPTl9TVEFURV9VTlNQRUNJRklFRBAAEh8KG0NPTlZFUlNBVElPTl9TVEFURV9HUkVFVElORxABEiAKHENPTlZFUlNBVElPTl9TVEFURV9BU0tfUEhPVE8QAhIhCh1DT05WRVJTQVRJT05fU1RBVEVfQVNLX0RSRUFNUxADEiAKHENPTlZFUlNBVElPTl9TVEFURV9BU0tfU1RZTEUQBBIeChpDT05WRVJTQVRJT05fU1RBVEVfQ09ORklSTRAFEiEKHUNPTlZFUlNBVElPTl9TVEFURV9HRU5FUkFUSU5HEAYSGwoXQ09OVkVSU0FUSU9OX1NUQVRFX0RPTkUQBxIdChlDT05WRVJTQVRJT05fU1RBVEVfRkFJTEVEEAgiWAoLTWVzc2FnZVJvbGUSHAoYTUVTU0FHRV9ST0xFX1VOU1BFQ0lGSUVEEAASFAoQTUVTU0FHRV9ST0xFX0JPVBABEhUKEU1FU1NBR0VfUk9MRV9VU0VSEAJCEQoPX2RyZWFtX2JvYXJkX2lkQg4KDF9hcmNoaXZlZF9hdEINCgtfZGVsZXRlZF9hdGIGcHJvdG8z", [file_google_protobuf_timestamp, file_modules_dream_board_proto_v1_dream_board]);

/**
 * A scripted chat that walks the user through creating a DreamBoard. At most
 * one non-archived Conversation exists per user; starting a new chat archives
 * the previous one.
 *
 * @generated from message modules.dream_board.proto.v1.Conversation
 */
export type Conversation = Message<"modules.dream_board.proto.v1.Conversation"> & {
  /**
   * The unique identifier for the Conversation.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The user ID of the owner.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * Position in the state machine — UI renders the matching input widgets.
   *
   * @generated from field: modules.dream_board.proto.v1.Conversation.ConversationState state = 3;
   */
  state: Conversation_ConversationState;

  /**
   * Append-only message log. i18n keys + params so the UI owns locale.
   *
   * @generated from field: repeated modules.dream_board.proto.v1.Conversation.Message messages = 4;
   */
  messages: Conversation_Message[];

  /**
   * Selections accumulated as the chat progresses.
   *
   * @generated from field: repeated string selected_dream_ids = 5;
   */
  selectedDreamIds: string[];

  /**
   * @generated from field: modules.dream_board.proto.v1.DreamBoard.DreamBoardStyle selected_style = 6;
   */
  selectedStyle: DreamBoard_DreamBoardStyle;

  /**
   * True when the user chose to skip the reference photo — we still generate
   * a board, just with a random person instead of their face.
   *
   * @generated from field: bool photo_skipped = 7;
   */
  photoSkipped: boolean;

  /**
   * Set when the chat finishes and a board is produced.
   *
   * @generated from field: optional string dream_board_id = 8;
   */
  dreamBoardId?: string;

  /**
   * Optimistic-concurrency version, bumped by every domain mutator.
   *
   * @generated from field: int64 version = 9;
   */
  version: bigint;

  /**
   * The timestamp when the Conversation was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * The timestamp when the Conversation was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;

  /**
   * The timestamp when the Conversation was last archived (new chat started, or done).
   *
   * @generated from field: optional google.protobuf.Timestamp archived_at = 22;
   */
  archivedAt?: Timestamp;

  /**
   * The timestamp when the Conversation was last deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 23;
   */
  deletedAt?: Timestamp;
};

/**
 * A scripted chat that walks the user through creating a DreamBoard. At most
 * one non-archived Conversation exists per user; starting a new chat archives
 * the previous one.
 *
 * @generated from message modules.dream_board.proto.v1.Conversation
 */
export type ConversationJson = {
  /**
   * The unique identifier for the Conversation.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * The user ID of the owner.
   *
   * @generated from field: string user_id = 2;
   */
  userId?: string;

  /**
   * Position in the state machine — UI renders the matching input widgets.
   *
   * @generated from field: modules.dream_board.proto.v1.Conversation.ConversationState state = 3;
   */
  state?: Conversation_ConversationStateJson;

  /**
   * Append-only message log. i18n keys + params so the UI owns locale.
   *
   * @generated from field: repeated modules.dream_board.proto.v1.Conversation.Message messages = 4;
   */
  messages?: Conversation_MessageJson[];

  /**
   * Selections accumulated as the chat progresses.
   *
   * @generated from field: repeated string selected_dream_ids = 5;
   */
  selectedDreamIds?: string[];

  /**
   * @generated from field: modules.dream_board.proto.v1.DreamBoard.DreamBoardStyle selected_style = 6;
   */
  selectedStyle?: DreamBoard_DreamBoardStyleJson;

  /**
   * True when the user chose to skip the reference photo — we still generate
   * a board, just with a random person instead of their face.
   *
   * @generated from field: bool photo_skipped = 7;
   */
  photoSkipped?: boolean;

  /**
   * Set when the chat finishes and a board is produced.
   *
   * @generated from field: optional string dream_board_id = 8;
   */
  dreamBoardId?: string;

  /**
   * Optimistic-concurrency version, bumped by every domain mutator.
   *
   * @generated from field: int64 version = 9;
   */
  version?: string;

  /**
   * The timestamp when the Conversation was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * The timestamp when the Conversation was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;

  /**
   * The timestamp when the Conversation was last archived (new chat started, or done).
   *
   * @generated from field: optional google.protobuf.Timestamp archived_at = 22;
   */
  archivedAt?: TimestampJson;

  /**
   * The timestamp when the Conversation was last deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 23;
   */
  deletedAt?: TimestampJson;
};

/**
 * Describes the message modules.dream_board.proto.v1.Conversation.
 * Use `create(ConversationSchema)` to create a new message.
 */
export const ConversationSchema: GenMessage<Conversation, {jsonType: ConversationJson}> = /*@__PURE__*/
  messageDesc(file_modules_dream_board_proto_v1_conversation, 0);

/**
 * A single chat bubble. Texts are stored as translation keys so the server
 * never bakes in the user's locale.
 *
 * @generated from message modules.dream_board.proto.v1.Conversation.Message
 */
export type Conversation_Message = Message<"modules.dream_board.proto.v1.Conversation.Message"> & {
  /**
   * @generated from field: modules.dream_board.proto.v1.Conversation.MessageRole role = 1;
   */
  role: Conversation_MessageRole;

  /**
   * i18n key under `pages.dreamBoard.chat.messages.*`. Empty when `text`
   * is used instead (for user-submitted free text — not used today but
   * reserved so adding it later doesn't need a proto bump).
   *
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * Parameters interpolated into the translated string.
   *
   * @generated from field: map<string, string> params = 3;
   */
  params: { [key: string]: string };

  /**
   * Fallback verbatim text (used only when `key` is empty).
   *
   * @generated from field: string text = 4;
   */
  text: string;

  /**
   * The timestamp when the message was sent.
   *
   * @generated from field: google.protobuf.Timestamp sent_at = 5;
   */
  sentAt?: Timestamp;
};

/**
 * A single chat bubble. Texts are stored as translation keys so the server
 * never bakes in the user's locale.
 *
 * @generated from message modules.dream_board.proto.v1.Conversation.Message
 */
export type Conversation_MessageJson = {
  /**
   * @generated from field: modules.dream_board.proto.v1.Conversation.MessageRole role = 1;
   */
  role?: Conversation_MessageRoleJson;

  /**
   * i18n key under `pages.dreamBoard.chat.messages.*`. Empty when `text`
   * is used instead (for user-submitted free text — not used today but
   * reserved so adding it later doesn't need a proto bump).
   *
   * @generated from field: string key = 2;
   */
  key?: string;

  /**
   * Parameters interpolated into the translated string.
   *
   * @generated from field: map<string, string> params = 3;
   */
  params?: { [key: string]: string };

  /**
   * Fallback verbatim text (used only when `key` is empty).
   *
   * @generated from field: string text = 4;
   */
  text?: string;

  /**
   * The timestamp when the message was sent.
   *
   * @generated from field: google.protobuf.Timestamp sent_at = 5;
   */
  sentAt?: TimestampJson;
};

/**
 * Describes the message modules.dream_board.proto.v1.Conversation.Message.
 * Use `create(Conversation_MessageSchema)` to create a new message.
 */
export const Conversation_MessageSchema: GenMessage<Conversation_Message, {jsonType: Conversation_MessageJson}> = /*@__PURE__*/
  messageDesc(file_modules_dream_board_proto_v1_conversation, 0, 0);

/**
 * The state of the Conversation.
 *
 * @generated from enum modules.dream_board.proto.v1.Conversation.ConversationState
 */
export enum Conversation_ConversationState {
  /**
   * No state specified.
   *
   * @generated from enum value: CONVERSATION_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Opening greeting; user clicks "Start" to advance.
   *
   * @generated from enum value: CONVERSATION_STATE_GREETING = 1;
   */
  GREETING = 1,

  /**
   * Asking whether to upload a photo. User can upload or skip.
   *
   * @generated from enum value: CONVERSATION_STATE_ASK_PHOTO = 2;
   */
  ASK_PHOTO = 2,

  /**
   * Asking which Dreams to include.
   *
   * @generated from enum value: CONVERSATION_STATE_ASK_DREAMS = 3;
   */
  ASK_DREAMS = 3,

  /**
   * Asking which visual style.
   *
   * @generated from enum value: CONVERSATION_STATE_ASK_STYLE = 4;
   */
  ASK_STYLE = 4,

  /**
   * Summary + confirm. User can go back or generate.
   *
   * @generated from enum value: CONVERSATION_STATE_CONFIRM = 5;
   */
  CONFIRM = 5,

  /**
   * Generation in-flight; UI shows a loading bubble.
   *
   * @generated from enum value: CONVERSATION_STATE_GENERATING = 6;
   */
  GENERATING = 6,

  /**
   * Board produced; chat ends here and the board is shown.
   *
   * @generated from enum value: CONVERSATION_STATE_DONE = 7;
   */
  DONE = 7,

  /**
   * Generation failed; user can retry or start over.
   *
   * @generated from enum value: CONVERSATION_STATE_FAILED = 8;
   */
  FAILED = 8,
}

/**
 * The state of the Conversation.
 *
 * @generated from enum modules.dream_board.proto.v1.Conversation.ConversationState
 */
export type Conversation_ConversationStateJson = "CONVERSATION_STATE_UNSPECIFIED" | "CONVERSATION_STATE_GREETING" | "CONVERSATION_STATE_ASK_PHOTO" | "CONVERSATION_STATE_ASK_DREAMS" | "CONVERSATION_STATE_ASK_STYLE" | "CONVERSATION_STATE_CONFIRM" | "CONVERSATION_STATE_GENERATING" | "CONVERSATION_STATE_DONE" | "CONVERSATION_STATE_FAILED";

/**
 * Describes the enum modules.dream_board.proto.v1.Conversation.ConversationState.
 */
export const Conversation_ConversationStateSchema: GenEnum<Conversation_ConversationState, Conversation_ConversationStateJson> = /*@__PURE__*/
  enumDesc(file_modules_dream_board_proto_v1_conversation, 0, 0);

/**
 * The role of the message.
 *
 * @generated from enum modules.dream_board.proto.v1.Conversation.MessageRole
 */
export enum Conversation_MessageRole {
  /**
   * No role specified.
   *
   * @generated from enum value: MESSAGE_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The message is from the bot.
   *
   * @generated from enum value: MESSAGE_ROLE_BOT = 1;
   */
  BOT = 1,

  /**
   * The message is from the user.
   *
   * @generated from enum value: MESSAGE_ROLE_USER = 2;
   */
  USER = 2,
}

/**
 * The role of the message.
 *
 * @generated from enum modules.dream_board.proto.v1.Conversation.MessageRole
 */
export type Conversation_MessageRoleJson = "MESSAGE_ROLE_UNSPECIFIED" | "MESSAGE_ROLE_BOT" | "MESSAGE_ROLE_USER";

/**
 * Describes the enum modules.dream_board.proto.v1.Conversation.MessageRole.
 */
export const Conversation_MessageRoleSchema: GenEnum<Conversation_MessageRole, Conversation_MessageRoleJson> = /*@__PURE__*/
  enumDesc(file_modules_dream_board_proto_v1_conversation, 0, 1);

