// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/dream_board/proto/v1/dream_board.proto (package modules.dream_board.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/dream_board/proto/v1/dream_board.proto.
 */
export const file_modules_dream_board_proto_v1_dream_board: GenFile = /*@__PURE__*/
  fileDesc("Ci5tb2R1bGVzL2RyZWFtX2JvYXJkL3Byb3RvL3YxL2RyZWFtX2JvYXJkLnByb3RvEhxtb2R1bGVzLmRyZWFtX2JvYXJkLnByb3RvLnYxIq0ECgpEcmVhbUJvYXJkEgoKAmlkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSEQoJZHJlYW1faWRzGAMgAygJEkcKBXN0eWxlGAQgASgOMjgubW9kdWxlcy5kcmVhbV9ib2FyZC5wcm90by52MS5EcmVhbUJvYXJkLkRyZWFtQm9hcmRTdHlsZRIUCgxzdG9yYWdlX3BhdGgYBSABKAkSDwoHdmVyc2lvbhgGIAEoAxIuCgpjcmVhdGVkX2F0GBQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GBUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIzCgpkZWxldGVkX2F0GBYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBItoBCg9EcmVhbUJvYXJkU3R5bGUSIQodRFJFQU1fQk9BUkRfU1RZTEVfVU5TUEVDSUZJRUQQABIfChtEUkVBTV9CT0FSRF9TVFlMRV9QSE9UT1JFQUwQARIfChtEUkVBTV9CT0FSRF9TVFlMRV9QQUlOVEVSTFkQAhIfChtEUkVBTV9CT0FSRF9TVFlMRV9TQ1JBUEJPT0sQAxIfChtEUkVBTV9CT0FSRF9TVFlMRV9DSU5FTUFUSUMQBBIgChxEUkVBTV9CT0FSRF9TVFlMRV9XQVRFUkNPTE9SEAVCDQoLX2RlbGV0ZWRfYXRiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * A generated vision-board image fusing the user's photo into a scene that
 * represents one or more of their Dreams.
 *
 * @generated from message modules.dream_board.proto.v1.DreamBoard
 */
export type DreamBoard = Message<"modules.dream_board.proto.v1.DreamBoard"> & {
  /**
   * The unique identifier for the DreamBoard.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The user ID of the owner.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * IDs of the Dreams composed into this board (not validated as UUIDs here
   * so the proto layer stays schema-only; zod enforces at the app boundary).
   *
   * @generated from field: repeated string dream_ids = 3;
   */
  dreamIds: string[];

  /**
   * Visual style the image was rendered in.
   *
   * @generated from field: modules.dream_board.proto.v1.DreamBoard.DreamBoardStyle style = 4;
   */
  style: DreamBoard_DreamBoardStyle;

  /**
   * Supabase Storage path for the generated PNG, e.g. `<user_id>/<id>.png`.
   * Bucket is private; UI consumes signed URLs produced by the repository.
   *
   * @generated from field: string storage_path = 5;
   */
  storagePath: string;

  /**
   * Optimistic-concurrency version, bumped by every domain mutator.
   *
   * @generated from field: int64 version = 6;
   */
  version: bigint;

  /**
   * The timestamp when the DreamBoard was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * The timestamp when the DreamBoard was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;

  /**
   * The timestamp when the DreamBoard was deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 22;
   */
  deletedAt?: Timestamp;
};

/**
 * A generated vision-board image fusing the user's photo into a scene that
 * represents one or more of their Dreams.
 *
 * @generated from message modules.dream_board.proto.v1.DreamBoard
 */
export type DreamBoardJson = {
  /**
   * The unique identifier for the DreamBoard.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * The user ID of the owner.
   *
   * @generated from field: string user_id = 2;
   */
  userId?: string;

  /**
   * IDs of the Dreams composed into this board (not validated as UUIDs here
   * so the proto layer stays schema-only; zod enforces at the app boundary).
   *
   * @generated from field: repeated string dream_ids = 3;
   */
  dreamIds?: string[];

  /**
   * Visual style the image was rendered in.
   *
   * @generated from field: modules.dream_board.proto.v1.DreamBoard.DreamBoardStyle style = 4;
   */
  style?: DreamBoard_DreamBoardStyleJson;

  /**
   * Supabase Storage path for the generated PNG, e.g. `<user_id>/<id>.png`.
   * Bucket is private; UI consumes signed URLs produced by the repository.
   *
   * @generated from field: string storage_path = 5;
   */
  storagePath?: string;

  /**
   * Optimistic-concurrency version, bumped by every domain mutator.
   *
   * @generated from field: int64 version = 6;
   */
  version?: string;

  /**
   * The timestamp when the DreamBoard was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * The timestamp when the DreamBoard was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;

  /**
   * The timestamp when the DreamBoard was deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 22;
   */
  deletedAt?: TimestampJson;
};

/**
 * Describes the message modules.dream_board.proto.v1.DreamBoard.
 * Use `create(DreamBoardSchema)` to create a new message.
 */
export const DreamBoardSchema: GenMessage<DreamBoard, {jsonType: DreamBoardJson}> = /*@__PURE__*/
  messageDesc(file_modules_dream_board_proto_v1_dream_board, 0);

/**
 * Rendering styles the user can pick from. The set is a closed enum — the
 * server builds the prompt so users can never push a free-text style.
 *
 * @generated from enum modules.dream_board.proto.v1.DreamBoard.DreamBoardStyle
 */
export enum DreamBoard_DreamBoardStyle {
  /**
   * No style specified.
   *
   * @generated from enum value: DREAM_BOARD_STYLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Photorealistic composition.
   *
   * @generated from enum value: DREAM_BOARD_STYLE_PHOTOREAL = 1;
   */
  PHOTOREAL = 1,

  /**
   * Painterly / oil-painting composition.
   *
   * @generated from enum value: DREAM_BOARD_STYLE_PAINTERLY = 2;
   */
  PAINTERLY = 2,

  /**
   * Scrapbook / collage composition.
   *
   * @generated from enum value: DREAM_BOARD_STYLE_SCRAPBOOK = 3;
   */
  SCRAPBOOK = 3,

  /**
   * Cinematic / dramatic lighting composition.
   *
   * @generated from enum value: DREAM_BOARD_STYLE_CINEMATIC = 4;
   */
  CINEMATIC = 4,

  /**
   * Watercolor composition.
   *
   * @generated from enum value: DREAM_BOARD_STYLE_WATERCOLOR = 5;
   */
  WATERCOLOR = 5,
}

/**
 * Rendering styles the user can pick from. The set is a closed enum — the
 * server builds the prompt so users can never push a free-text style.
 *
 * @generated from enum modules.dream_board.proto.v1.DreamBoard.DreamBoardStyle
 */
export type DreamBoard_DreamBoardStyleJson = "DREAM_BOARD_STYLE_UNSPECIFIED" | "DREAM_BOARD_STYLE_PHOTOREAL" | "DREAM_BOARD_STYLE_PAINTERLY" | "DREAM_BOARD_STYLE_SCRAPBOOK" | "DREAM_BOARD_STYLE_CINEMATIC" | "DREAM_BOARD_STYLE_WATERCOLOR";

/**
 * Describes the enum modules.dream_board.proto.v1.DreamBoard.DreamBoardStyle.
 */
export const DreamBoard_DreamBoardStyleSchema: GenEnum<DreamBoard_DreamBoardStyle, DreamBoard_DreamBoardStyleJson> = /*@__PURE__*/
  enumDesc(file_modules_dream_board_proto_v1_dream_board, 0, 0);

