// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/dream_board/proto/v1/user_photo.proto (package modules.dream_board.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/dream_board/proto/v1/user_photo.proto.
 */
export const file_modules_dream_board_proto_v1_user_photo: GenFile = /*@__PURE__*/
  fileDesc("Ci1tb2R1bGVzL2RyZWFtX2JvYXJkL3Byb3RvL3YxL3VzZXJfcGhvdG8ucHJvdG8SHG1vZHVsZXMuZHJlYW1fYm9hcmQucHJvdG8udjEiowEKCVVzZXJQaG90bxIPCgd1c2VyX2lkGAEgASgJEhQKDHN0b3JhZ2VfcGF0aBgCIAEoCRIPCgd2ZXJzaW9uGAMgASgDEi4KCmNyZWF0ZWRfYXQYFCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYFSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * The reference photo a user uploads once so it can be composited into every
 * DreamBoard they generate. Scoped to this module because its only purpose is
 * driving Nano Banana image fusion — not a general profile avatar.
 *
 * @generated from message modules.dream_board.proto.v1.UserPhoto
 */
export type UserPhoto = Message<"modules.dream_board.proto.v1.UserPhoto"> & {
  /**
   * Owner of the photo. One row per user.
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Supabase Storage path, e.g. `<user_id>.jpg`. Private bucket; read via
   * signed URL produced by the repository.
   *
   * @generated from field: string storage_path = 2;
   */
  storagePath: string;

  /**
   * Optimistic-concurrency version, bumped on each replacement.
   *
   * @generated from field: int64 version = 3;
   */
  version: bigint;

  /**
   * The timestamp when the UserPhoto was first uploaded.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * The timestamp when the UserPhoto was last replaced.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;
};

/**
 * The reference photo a user uploads once so it can be composited into every
 * DreamBoard they generate. Scoped to this module because its only purpose is
 * driving Nano Banana image fusion — not a general profile avatar.
 *
 * @generated from message modules.dream_board.proto.v1.UserPhoto
 */
export type UserPhotoJson = {
  /**
   * Owner of the photo. One row per user.
   *
   * @generated from field: string user_id = 1;
   */
  userId?: string;

  /**
   * Supabase Storage path, e.g. `<user_id>.jpg`. Private bucket; read via
   * signed URL produced by the repository.
   *
   * @generated from field: string storage_path = 2;
   */
  storagePath?: string;

  /**
   * Optimistic-concurrency version, bumped on each replacement.
   *
   * @generated from field: int64 version = 3;
   */
  version?: string;

  /**
   * The timestamp when the UserPhoto was first uploaded.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * The timestamp when the UserPhoto was last replaced.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;
};

/**
 * Describes the message modules.dream_board.proto.v1.UserPhoto.
 * Use `create(UserPhotoSchema)` to create a new message.
 */
export const UserPhotoSchema: GenMessage<UserPhoto, {jsonType: UserPhotoJson}> = /*@__PURE__*/
  messageDesc(file_modules_dream_board_proto_v1_user_photo, 0);

