// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/dreams/proto/v1/dream.proto (package modules.dreams.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/dreams/proto/v1/dream.proto.
 */
export const file_modules_dreams_proto_v1_dream: GenFile = /*@__PURE__*/
  fileDesc("CiNtb2R1bGVzL2RyZWFtcy9wcm90by92MS9kcmVhbS5wcm90bxIXbW9kdWxlcy5kcmVhbXMucHJvdG8udjEinAYKBURyZWFtEgoKAmlkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSDQoFdGl0bGUYAyABKAkSOgoGc3RhdHVzGAQgASgOMioubW9kdWxlcy5kcmVhbXMucHJvdG8udjEuRHJlYW0uRHJlYW1TdGF0dXMSRAoMYXJlYV9vZl9saWZlGAUgASgOMi4ubW9kdWxlcy5kcmVhbXMucHJvdG8udjEuRHJlYW0uRHJlYW1BcmVhT2ZMaWZlEhAKCGRlYWRsaW5lGAYgASgJEhMKC2FjdGlvbl9wbGFuGAcgASgJEg8KB3ZlcnNpb24YCCABKAMSLgoKY3JlYXRlZF9hdBgUIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgVIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMwoKZGVsZXRlZF9hdBgWIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAIgBASJ+CgtEcmVhbVN0YXR1cxIcChhEUkVBTV9TVEFUVVNfVU5TUEVDSUZJRUQQABIcChhEUkVBTV9TVEFUVVNfSU5fUFJPR1JFU1MQARIaChZEUkVBTV9TVEFUVVNfQ09NUExFVEVEEAISFwoTRFJFQU1fU1RBVFVTX1BBVVNFRBADIogCCg9EcmVhbUFyZWFPZkxpZmUSIgoeRFJFQU1fQVJFQV9PRl9MSUZFX1VOU1BFQ0lGSUVEEAASLworRFJFQU1fQVJFQV9PRl9MSUZFX0ZBTUlMWV9BTkRfUkVMQU5USU9OU0hJUBABEiwKKERSRUFNX0FSRUFfT0ZfTElGRV9IRUFMVEhfQU5EX1dFTExfQkVJTkcQAhIrCidEUkVBTV9BUkVBX09GX0xJRkVfQlVTSU5FU1NfQU5EX0ZJTkFOQ0UQAxIjCh9EUkVBTV9BUkVBX09GX0xJRkVfU1BJUklUVUFMSVRZEAQSIAocRFJFQU1fQVJFQV9PRl9MSUZFX0xJRkVTVFlMRRAFQg0KC19kZWxldGVkX2F0YgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * The Dream entity.
 *
 * @generated from message modules.dreams.proto.v1.Dream
 */
export type Dream = Message<"modules.dreams.proto.v1.Dream"> & {
  /**
   * The unique identifier for the Dream.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The user ID of the owner of the Dream.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * The title of the Dream.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * The status of the Dream.
   *
   * @generated from field: modules.dreams.proto.v1.Dream.DreamStatus status = 4;
   */
  status: Dream_DreamStatus;

  /**
   * The area of life the Dream is related to.
   *
   * @generated from field: modules.dreams.proto.v1.Dream.DreamAreaOfLife area_of_life = 5;
   */
  areaOfLife: Dream_DreamAreaOfLife;

  /**
   * ISO date (YYYY-MM-DD). Date-only, not a Timestamp.
   *
   * @generated from field: string deadline = 6;
   */
  deadline: string;

  /**
   * The action plan for the Dream.
   *
   * @generated from field: string action_plan = 7;
   */
  actionPlan: string;

  /**
   * The version of the Dream.
   *
   * @generated from field: int64 version = 8;
   */
  version: bigint;

  /**
   * The timestamp when the Dream was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * The timestamp when the Dream was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;

  /**
   * The timestamp when the Dream was deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 22;
   */
  deletedAt?: Timestamp;
};

/**
 * The Dream entity.
 *
 * @generated from message modules.dreams.proto.v1.Dream
 */
export type DreamJson = {
  /**
   * The unique identifier for the Dream.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * The user ID of the owner of the Dream.
   *
   * @generated from field: string user_id = 2;
   */
  userId?: string;

  /**
   * The title of the Dream.
   *
   * @generated from field: string title = 3;
   */
  title?: string;

  /**
   * The status of the Dream.
   *
   * @generated from field: modules.dreams.proto.v1.Dream.DreamStatus status = 4;
   */
  status?: Dream_DreamStatusJson;

  /**
   * The area of life the Dream is related to.
   *
   * @generated from field: modules.dreams.proto.v1.Dream.DreamAreaOfLife area_of_life = 5;
   */
  areaOfLife?: Dream_DreamAreaOfLifeJson;

  /**
   * ISO date (YYYY-MM-DD). Date-only, not a Timestamp.
   *
   * @generated from field: string deadline = 6;
   */
  deadline?: string;

  /**
   * The action plan for the Dream.
   *
   * @generated from field: string action_plan = 7;
   */
  actionPlan?: string;

  /**
   * The version of the Dream.
   *
   * @generated from field: int64 version = 8;
   */
  version?: string;

  /**
   * The timestamp when the Dream was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * The timestamp when the Dream was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;

  /**
   * The timestamp when the Dream was deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 22;
   */
  deletedAt?: TimestampJson;
};

/**
 * Describes the message modules.dreams.proto.v1.Dream.
 * Use `create(DreamSchema)` to create a new message.
 */
export const DreamSchema: GenMessage<Dream, {jsonType: DreamJson}> = /*@__PURE__*/
  messageDesc(file_modules_dreams_proto_v1_dream, 0);

/**
 * Lifecycle states a Dream moves through.
 *
 * @generated from enum modules.dreams.proto.v1.Dream.DreamStatus
 */
export enum Dream_DreamStatus {
  /**
   * The Dream is not specified.
   *
   * @generated from enum value: DREAM_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The Dream is in progress.
   *
   * @generated from enum value: DREAM_STATUS_IN_PROGRESS = 1;
   */
  IN_PROGRESS = 1,

  /**
   * The Dream is completed.
   *
   * @generated from enum value: DREAM_STATUS_COMPLETED = 2;
   */
  COMPLETED = 2,

  /**
   * The Dream is paused.
   *
   * @generated from enum value: DREAM_STATUS_PAUSED = 3;
   */
  PAUSED = 3,
}

/**
 * Lifecycle states a Dream moves through.
 *
 * @generated from enum modules.dreams.proto.v1.Dream.DreamStatus
 */
export type Dream_DreamStatusJson = "DREAM_STATUS_UNSPECIFIED" | "DREAM_STATUS_IN_PROGRESS" | "DREAM_STATUS_COMPLETED" | "DREAM_STATUS_PAUSED";

/**
 * Describes the enum modules.dreams.proto.v1.Dream.DreamStatus.
 */
export const Dream_DreamStatusSchema: GenEnum<Dream_DreamStatus, Dream_DreamStatusJson> = /*@__PURE__*/
  enumDesc(file_modules_dreams_proto_v1_dream, 0, 0);

/**
 * The five life-areas a Dream is grouped under.
 *
 * @generated from enum modules.dreams.proto.v1.Dream.DreamAreaOfLife
 */
export enum Dream_DreamAreaOfLife {
  /**
   * The Dream is not related to any life-area.
   *
   * @generated from enum value: DREAM_AREA_OF_LIFE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The Dream is related to the family and relationships.
   *
   * @generated from enum value: DREAM_AREA_OF_LIFE_FAMILY_AND_RELANTIONSHIP = 1;
   */
  FAMILY_AND_RELANTIONSHIP = 1,

  /**
   * The Dream is related to the health and well-being.
   *
   * @generated from enum value: DREAM_AREA_OF_LIFE_HEALTH_AND_WELL_BEING = 2;
   */
  HEALTH_AND_WELL_BEING = 2,

  /**
   * The Dream is related to the business and finance.
   *
   * @generated from enum value: DREAM_AREA_OF_LIFE_BUSINESS_AND_FINANCE = 3;
   */
  BUSINESS_AND_FINANCE = 3,

  /**
   * The Dream is related to the spirituality.
   *
   * @generated from enum value: DREAM_AREA_OF_LIFE_SPIRITUALITY = 4;
   */
  SPIRITUALITY = 4,

  /**
   * The Dream is related to the lifestyle.
   *
   * @generated from enum value: DREAM_AREA_OF_LIFE_LIFESTYLE = 5;
   */
  LIFESTYLE = 5,
}

/**
 * The five life-areas a Dream is grouped under.
 *
 * @generated from enum modules.dreams.proto.v1.Dream.DreamAreaOfLife
 */
export type Dream_DreamAreaOfLifeJson = "DREAM_AREA_OF_LIFE_UNSPECIFIED" | "DREAM_AREA_OF_LIFE_FAMILY_AND_RELANTIONSHIP" | "DREAM_AREA_OF_LIFE_HEALTH_AND_WELL_BEING" | "DREAM_AREA_OF_LIFE_BUSINESS_AND_FINANCE" | "DREAM_AREA_OF_LIFE_SPIRITUALITY" | "DREAM_AREA_OF_LIFE_LIFESTYLE";

/**
 * Describes the enum modules.dreams.proto.v1.Dream.DreamAreaOfLife.
 */
export const Dream_DreamAreaOfLifeSchema: GenEnum<Dream_DreamAreaOfLife, Dream_DreamAreaOfLifeJson> = /*@__PURE__*/
  enumDesc(file_modules_dreams_proto_v1_dream, 0, 1);

