// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/discovery/proto/v1/question.proto (package modules.discovery.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Phase, PhaseJson } from "./session_pb";
import { file_modules_discovery_proto_v1_session } from "./session_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/discovery/proto/v1/question.proto.
 */
export const file_modules_discovery_proto_v1_question: GenFile = /*@__PURE__*/
  fileDesc("Ciltb2R1bGVzL2Rpc2NvdmVyeS9wcm90by92MS9xdWVzdGlvbi5wcm90bxIabW9kdWxlcy5kaXNjb3ZlcnkucHJvdG8udjEilAEKCFF1ZXN0aW9uEgoKAmlkGAEgASgJEjAKBXBoYXNlGAIgASgOMiEubW9kdWxlcy5kaXNjb3ZlcnkucHJvdG8udjEuUGhhc2USDgoGcHJvbXB0GAMgASgJEhMKC3BsYWNlaG9sZGVyGAQgASgJEhYKDmZvbGxvd191cF9oaW50GAUgASgJEg0KBW9yZGVyGAYgASgFYgZwcm90bzM", [file_modules_discovery_proto_v1_session]);

/**
 * @generated from message modules.discovery.proto.v1.Question
 */
export type Question = Message<"modules.discovery.proto.v1.Question"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: modules.discovery.proto.v1.Phase phase = 2;
   */
  phase: Phase;

  /**
   * @generated from field: string prompt = 3;
   */
  prompt: string;

  /**
   * @generated from field: string placeholder = 4;
   */
  placeholder: string;

  /**
   * @generated from field: string follow_up_hint = 5;
   */
  followUpHint: string;

  /**
   * @generated from field: int32 order = 6;
   */
  order: number;
};

/**
 * @generated from message modules.discovery.proto.v1.Question
 */
export type QuestionJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: modules.discovery.proto.v1.Phase phase = 2;
   */
  phase?: PhaseJson;

  /**
   * @generated from field: string prompt = 3;
   */
  prompt?: string;

  /**
   * @generated from field: string placeholder = 4;
   */
  placeholder?: string;

  /**
   * @generated from field: string follow_up_hint = 5;
   */
  followUpHint?: string;

  /**
   * @generated from field: int32 order = 6;
   */
  order?: number;
};

/**
 * Describes the message modules.discovery.proto.v1.Question.
 * Use `create(QuestionSchema)` to create a new message.
 */
export const QuestionSchema: GenMessage<Question, {jsonType: QuestionJson}> = /*@__PURE__*/
  messageDesc(file_modules_discovery_proto_v1_question, 0);

