// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/actions/proto/v1/action.proto (package modules.actions.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Dream_DreamAreaOfLife, Dream_DreamAreaOfLifeJson } from "../../../dreams/proto/v1/dream_pb";
import { file_modules_dreams_proto_v1_dream } from "../../../dreams/proto/v1/dream_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/actions/proto/v1/action.proto.
 */
export const file_modules_actions_proto_v1_action: GenFile = /*@__PURE__*/
  fileDesc("CiVtb2R1bGVzL2FjdGlvbnMvcHJvdG8vdjEvYWN0aW9uLnByb3RvEhhtb2R1bGVzLmFjdGlvbnMucHJvdG8udjEilwcKBkFjdGlvbhIKCgJpZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEhUKCGRyZWFtX2lkGAMgASgJSACIAQESHQoQcGFyZW50X2FjdGlvbl9pZBgEIAEoCUgBiAEBEg0KBXRpdGxlGAUgASgJEj0KBnN0YXR1cxgGIAEoDjItLm1vZHVsZXMuYWN0aW9ucy5wcm90by52MS5BY3Rpb24uQWN0aW9uU3RhdHVzEkoKEmRyZWFtX2FyZWFfb2ZfbGlmZRgHIAEoDjIuLm1vZHVsZXMuZHJlYW1zLnByb3RvLnYxLkRyZWFtLkRyZWFtQXJlYU9mTGlmZRJFCgpyZWN1cnJlbmNlGAggASgOMjEubW9kdWxlcy5hY3Rpb25zLnByb3RvLnYxLkFjdGlvbi5BY3Rpb25SZWN1cnJlbmNlEhUKCGR1ZV9kYXRlGAkgASgJSAKIAQESDwoHdmVyc2lvbhgKIAEoAxIuCgpjcmVhdGVkX2F0GBQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GBUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIzCgpkZWxldGVkX2F0GBYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgDiAEBIogBCgxBY3Rpb25TdGF0dXMSHQoZQUNUSU9OX1NUQVRVU19VTlNQRUNJRklFRBAAEh0KGUFDVElPTl9TVEFUVVNfTk9UX1NUQVJURUQQARIdChlBQ1RJT05fU1RBVFVTX0lOX1BST0dSRVNTEAISGwoXQUNUSU9OX1NUQVRVU19DT01QTEVURUQQAyLSAQoQQWN0aW9uUmVjdXJyZW5jZRIhCh1BQ1RJT05fUkVDVVJSRU5DRV9VTlNQRUNJRklFRBAAEhoKFkFDVElPTl9SRUNVUlJFTkNFX09OQ0UQARIbChdBQ1RJT05fUkVDVVJSRU5DRV9EQUlMWRACEh4KGkFDVElPTl9SRUNVUlJFTkNFX1dFRUtEQVlTEAMSHgoaQUNUSU9OX1JFQ1VSUkVOQ0VfV0VFS0VORFMQBBIiCh5BQ1RJT05fUkVDVVJSRU5DRV9TUEVDSUFMX0RBWVMQBUILCglfZHJlYW1faWRCEwoRX3BhcmVudF9hY3Rpb25faWRCCwoJX2R1ZV9kYXRlQg0KC19kZWxldGVkX2F0YgZwcm90bzM", [file_google_protobuf_timestamp, file_modules_dreams_proto_v1_dream]);

/**
 * The Action entity.
 *
 * @generated from message modules.actions.proto.v1.Action
 */
export type Action = Message<"modules.actions.proto.v1.Action"> & {
  /**
   * The unique identifier for the Action.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The unique identifier for the user the Action is related to.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * The unique identifier for the Dream the Action is related to.
   *
   * @generated from field: optional string dream_id = 3;
   */
  dreamId?: string;

  /**
   * The unique identifier for the parent Action.
   *
   * @generated from field: optional string parent_action_id = 4;
   */
  parentActionId?: string;

  /**
   * The title of the Action.
   *
   * @generated from field: string title = 5;
   */
  title: string;

  /**
   * The status of the Action.
   *
   * @generated from field: modules.actions.proto.v1.Action.ActionStatus status = 6;
   */
  status: Action_ActionStatus;

  /**
   * Snapshot of the parent Dream's area of life. `UNSPECIFIED` = not linked.
   *
   * @generated from field: modules.dreams.proto.v1.Dream.DreamAreaOfLife dream_area_of_life = 7;
   */
  dreamAreaOfLife: Dream_DreamAreaOfLife;

  /**
   * The recurrence of the Action.
   *
   * @generated from field: modules.actions.proto.v1.Action.ActionRecurrence recurrence = 8;
   */
  recurrence: Action_ActionRecurrence;

  /**
   * The due date of the Action.
   * ISO date (YYYY-MM-DD). Empty string == unset.
   *
   * @generated from field: optional string due_date = 9;
   */
  dueDate?: string;

  /**
   * The version of the Action.
   *
   * @generated from field: int64 version = 10;
   */
  version: bigint;

  /**
   * The timestamp when the Action was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * The timestamp when the Action was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;

  /**
   * The timestamp when the Action was deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 22;
   */
  deletedAt?: Timestamp;
};

/**
 * The Action entity.
 *
 * @generated from message modules.actions.proto.v1.Action
 */
export type ActionJson = {
  /**
   * The unique identifier for the Action.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * The unique identifier for the user the Action is related to.
   *
   * @generated from field: string user_id = 2;
   */
  userId?: string;

  /**
   * The unique identifier for the Dream the Action is related to.
   *
   * @generated from field: optional string dream_id = 3;
   */
  dreamId?: string;

  /**
   * The unique identifier for the parent Action.
   *
   * @generated from field: optional string parent_action_id = 4;
   */
  parentActionId?: string;

  /**
   * The title of the Action.
   *
   * @generated from field: string title = 5;
   */
  title?: string;

  /**
   * The status of the Action.
   *
   * @generated from field: modules.actions.proto.v1.Action.ActionStatus status = 6;
   */
  status?: Action_ActionStatusJson;

  /**
   * Snapshot of the parent Dream's area of life. `UNSPECIFIED` = not linked.
   *
   * @generated from field: modules.dreams.proto.v1.Dream.DreamAreaOfLife dream_area_of_life = 7;
   */
  dreamAreaOfLife?: Dream_DreamAreaOfLifeJson;

  /**
   * The recurrence of the Action.
   *
   * @generated from field: modules.actions.proto.v1.Action.ActionRecurrence recurrence = 8;
   */
  recurrence?: Action_ActionRecurrenceJson;

  /**
   * The due date of the Action.
   * ISO date (YYYY-MM-DD). Empty string == unset.
   *
   * @generated from field: optional string due_date = 9;
   */
  dueDate?: string;

  /**
   * The version of the Action.
   *
   * @generated from field: int64 version = 10;
   */
  version?: string;

  /**
   * The timestamp when the Action was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * The timestamp when the Action was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;

  /**
   * The timestamp when the Action was deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 22;
   */
  deletedAt?: TimestampJson;
};

/**
 * Describes the message modules.actions.proto.v1.Action.
 * Use `create(ActionSchema)` to create a new message.
 */
export const ActionSchema: GenMessage<Action, {jsonType: ActionJson}> = /*@__PURE__*/
  messageDesc(file_modules_actions_proto_v1_action, 0);

/**
 * Lifecycle states for an Action.
 *
 * @generated from enum modules.actions.proto.v1.Action.ActionStatus
 */
export enum Action_ActionStatus {
  /**
   * The Action is not specified.
   *
   * @generated from enum value: ACTION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The Action is not started.
   *
   * @generated from enum value: ACTION_STATUS_NOT_STARTED = 1;
   */
  NOT_STARTED = 1,

  /**
   * The Action is in progress.
   *
   * @generated from enum value: ACTION_STATUS_IN_PROGRESS = 2;
   */
  IN_PROGRESS = 2,

  /**
   * The Action is completed.
   *
   * @generated from enum value: ACTION_STATUS_COMPLETED = 3;
   */
  COMPLETED = 3,
}

/**
 * Lifecycle states for an Action.
 *
 * @generated from enum modules.actions.proto.v1.Action.ActionStatus
 */
export type Action_ActionStatusJson = "ACTION_STATUS_UNSPECIFIED" | "ACTION_STATUS_NOT_STARTED" | "ACTION_STATUS_IN_PROGRESS" | "ACTION_STATUS_COMPLETED";

/**
 * Describes the enum modules.actions.proto.v1.Action.ActionStatus.
 */
export const Action_ActionStatusSchema: GenEnum<Action_ActionStatus, Action_ActionStatusJson> = /*@__PURE__*/
  enumDesc(file_modules_actions_proto_v1_action, 0, 0);

/**
 * How often an Action repeats.
 *
 * @generated from enum modules.actions.proto.v1.Action.ActionRecurrence
 */
export enum Action_ActionRecurrence {
  /**
   * The Action is not specified.
   *
   * @generated from enum value: ACTION_RECURRENCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The Action repeats once.
   *
   * @generated from enum value: ACTION_RECURRENCE_ONCE = 1;
   */
  ONCE = 1,

  /**
   * The Action repeats daily.
   *
   * @generated from enum value: ACTION_RECURRENCE_DAILY = 2;
   */
  DAILY = 2,

  /**
   * The Action repeats on weekdays.
   *
   * @generated from enum value: ACTION_RECURRENCE_WEEKDAYS = 3;
   */
  WEEKDAYS = 3,

  /**
   * The Action repeats on weekends.
   *
   * @generated from enum value: ACTION_RECURRENCE_WEEKENDS = 4;
   */
  WEEKENDS = 4,

  /**
   * The Action repeats on special days.
   *
   * @generated from enum value: ACTION_RECURRENCE_SPECIAL_DAYS = 5;
   */
  SPECIAL_DAYS = 5,
}

/**
 * How often an Action repeats.
 *
 * @generated from enum modules.actions.proto.v1.Action.ActionRecurrence
 */
export type Action_ActionRecurrenceJson = "ACTION_RECURRENCE_UNSPECIFIED" | "ACTION_RECURRENCE_ONCE" | "ACTION_RECURRENCE_DAILY" | "ACTION_RECURRENCE_WEEKDAYS" | "ACTION_RECURRENCE_WEEKENDS" | "ACTION_RECURRENCE_SPECIAL_DAYS";

/**
 * Describes the enum modules.actions.proto.v1.Action.ActionRecurrence.
 */
export const Action_ActionRecurrenceSchema: GenEnum<Action_ActionRecurrence, Action_ActionRecurrenceJson> = /*@__PURE__*/
  enumDesc(file_modules_actions_proto_v1_action, 0, 1);

