// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/dashboard/proto/v1/sentence.proto (package modules.dashboard.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/dashboard/proto/v1/sentence.proto.
 */
export const file_modules_dashboard_proto_v1_sentence: GenFile = /*@__PURE__*/
  fileDesc("Ciltb2R1bGVzL2Rhc2hib2FyZC9wcm90by92MS9zZW50ZW5jZS5wcm90bxIabW9kdWxlcy5kYXNoYm9hcmQucHJvdG8udjEioQIKCFNlbnRlbmNlEgoKAmlkGAEgASgJEgwKBHRleHQYAiABKAkSNQoMbGFzdF91c2VkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBEg8KB3ZlcnNpb24YBCABKAMSLgoKY3JlYXRlZF9hdBgUIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgVIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMwoKZGVsZXRlZF9hdBgWIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAYgBAUIPCg1fbGFzdF91c2VkX2F0Qg0KC19kZWxldGVkX2F0YgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * The Sentence entity.
 *
 * @generated from message modules.dashboard.proto.v1.Sentence
 */
export type Sentence = Message<"modules.dashboard.proto.v1.Sentence"> & {
  /**
   * The unique identifier for the Sentence.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The text of the Sentence.
   *
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * The timestamp when the Sentence was last used.
   *
   * @generated from field: optional google.protobuf.Timestamp last_used_at = 3;
   */
  lastUsedAt?: Timestamp;

  /**
   * The version of the Sentence.
   *
   * @generated from field: int64 version = 4;
   */
  version: bigint;

  /**
   * The timestamp when the Sentence was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * The timestamp when the Sentence was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;

  /**
   * The timestamp when the Sentence was deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 22;
   */
  deletedAt?: Timestamp;
};

/**
 * The Sentence entity.
 *
 * @generated from message modules.dashboard.proto.v1.Sentence
 */
export type SentenceJson = {
  /**
   * The unique identifier for the Sentence.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * The text of the Sentence.
   *
   * @generated from field: string text = 2;
   */
  text?: string;

  /**
   * The timestamp when the Sentence was last used.
   *
   * @generated from field: optional google.protobuf.Timestamp last_used_at = 3;
   */
  lastUsedAt?: TimestampJson;

  /**
   * The version of the Sentence.
   *
   * @generated from field: int64 version = 4;
   */
  version?: string;

  /**
   * The timestamp when the Sentence was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * The timestamp when the Sentence was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;

  /**
   * The timestamp when the Sentence was deleted.
   *
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 22;
   */
  deletedAt?: TimestampJson;
};

/**
 * Describes the message modules.dashboard.proto.v1.Sentence.
 * Use `create(SentenceSchema)` to create a new message.
 */
export const SentenceSchema: GenMessage<Sentence, {jsonType: SentenceJson}> = /*@__PURE__*/
  messageDesc(file_modules_dashboard_proto_v1_sentence, 0);

