// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/billing/proto/v1/customer.proto (package modules.billing.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { BillingProvider, BillingProviderJson } from "../../../shared/proto/v1/billing_provider_pb";
import { file_modules_shared_proto_v1_billing_provider } from "../../../shared/proto/v1/billing_provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/billing/proto/v1/customer.proto.
 */
export const file_modules_billing_proto_v1_customer: GenFile = /*@__PURE__*/
  fileDesc("Cidtb2R1bGVzL2JpbGxpbmcvcHJvdG8vdjEvY3VzdG9tZXIucHJvdG8SGG1vZHVsZXMuYmlsbGluZy5wcm90by52MSLhAQoIQ3VzdG9tZXISCgoCaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCRI6Cghwcm92aWRlchgDIAEoDjIoLm1vZHVsZXMuc2hhcmVkLnByb3RvLnYxLkJpbGxpbmdQcm92aWRlchIcChRwcm92aWRlcl9jdXN0b21lcl9pZBgEIAEoCRIuCgpjcmVhdGVkX2F0GBQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GBUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcGIGcHJvdG8z", [file_google_protobuf_timestamp, file_modules_shared_proto_v1_billing_provider]);

/**
 * Ties a Supabase auth user to an external payment provider customer
 * (e.g. a Stripe customer id).
 *
 * @generated from message modules.billing.proto.v1.Customer
 */
export type Customer = Message<"modules.billing.proto.v1.Customer"> & {
  /**
   * Internal row id (uuid).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Supabase auth user id.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.shared.proto.v1.BillingProvider provider = 3;
   */
  provider: BillingProvider;

  /**
   * The id issued by the provider for this customer.
   *
   * @generated from field: string provider_customer_id = 4;
   */
  providerCustomerId: string;

  /**
   * When the customer row was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * When the customer row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;
};

/**
 * Ties a Supabase auth user to an external payment provider customer
 * (e.g. a Stripe customer id).
 *
 * @generated from message modules.billing.proto.v1.Customer
 */
export type CustomerJson = {
  /**
   * Internal row id (uuid).
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * Supabase auth user id.
   *
   * @generated from field: string user_id = 2;
   */
  userId?: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.shared.proto.v1.BillingProvider provider = 3;
   */
  provider?: BillingProviderJson;

  /**
   * The id issued by the provider for this customer.
   *
   * @generated from field: string provider_customer_id = 4;
   */
  providerCustomerId?: string;

  /**
   * When the customer row was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * When the customer row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;
};

/**
 * Describes the message modules.billing.proto.v1.Customer.
 * Use `create(CustomerSchema)` to create a new message.
 */
export const CustomerSchema: GenMessage<Customer, {jsonType: CustomerJson}> = /*@__PURE__*/
  messageDesc(file_modules_billing_proto_v1_customer, 0);

