// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/billing/proto/v1/invoice.proto (package modules.billing.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { BillingProvider, BillingProviderJson } from "../../../shared/proto/v1/billing_provider_pb";
import { file_modules_shared_proto_v1_billing_provider } from "../../../shared/proto/v1/billing_provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/billing/proto/v1/invoice.proto.
 */
export const file_modules_billing_proto_v1_invoice: GenFile = /*@__PURE__*/
  fileDesc("CiZtb2R1bGVzL2JpbGxpbmcvcHJvdG8vdjEvaW52b2ljZS5wcm90bxIYbW9kdWxlcy5iaWxsaW5nLnByb3RvLnYxIpoGCgdJbnZvaWNlEgoKAmlkGAEgASgJEjoKCHByb3ZpZGVyGAIgASgOMigubW9kdWxlcy5zaGFyZWQucHJvdG8udjEuQmlsbGluZ1Byb3ZpZGVyEg8KB3VzZXJfaWQYAyABKAkSFwoPc3Vic2NyaXB0aW9uX2lkGAQgASgJEj8KBnN0YXR1cxgFIAEoDjIvLm1vZHVsZXMuYmlsbGluZy5wcm90by52MS5JbnZvaWNlLkludm9pY2VTdGF0dXMSEgoKYW1vdW50X2R1ZRgGIAEoAxITCgthbW91bnRfcGFpZBgHIAEoAxIQCghjdXJyZW5jeRgIIAEoCRIOCgZudW1iZXIYCSABKAkSGgoSaG9zdGVkX2ludm9pY2VfdXJsGAogASgJEhMKC2ludm9pY2VfcGRmGAsgASgJEi4KCmNyZWF0ZWRfYXQYFCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYFSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEkYKDnN0YXR1c19oaXN0b3J5GBYgAygLMi4ubW9kdWxlcy5iaWxsaW5nLnByb3RvLnYxLkludm9pY2UuU3RhdHVzQ2hhbmdlGn8KDFN0YXR1c0NoYW5nZRI/CgZzdGF0dXMYASABKA4yLy5tb2R1bGVzLmJpbGxpbmcucHJvdG8udjEuSW52b2ljZS5JbnZvaWNlU3RhdHVzEi4KCmNoYW5nZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIrYBCg1JbnZvaWNlU3RhdHVzEh4KGklOVk9JQ0VfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGAoUSU5WT0lDRV9TVEFUVVNfRFJBRlQQARIXChNJTlZPSUNFX1NUQVRVU19PUEVOEAISFwoTSU5WT0lDRV9TVEFUVVNfUEFJRBADEiAKHElOVk9JQ0VfU1RBVFVTX1VOQ09MTEVDVElCTEUQBBIXChNJTlZPSUNFX1NUQVRVU19WT0lEEAViBnByb3RvMw", [file_google_protobuf_timestamp, file_modules_shared_proto_v1_billing_provider]);

/**
 * A billing invoice.
 *
 * @generated from message modules.billing.proto.v1.Invoice
 */
export type Invoice = Message<"modules.billing.proto.v1.Invoice"> & {
  /**
   * Provider-issued invoice id.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.shared.proto.v1.BillingProvider provider = 2;
   */
  provider: BillingProvider;

  /**
   * Supabase auth user id.
   *
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * Subscription the invoice belongs to (if any).
   *
   * @generated from field: string subscription_id = 4;
   */
  subscriptionId: string;

  /**
   * Lifecycle status.
   *
   * @generated from field: modules.billing.proto.v1.Invoice.InvoiceStatus status = 5;
   */
  status: Invoice_InvoiceStatus;

  /**
   * Amount due in cents.
   *
   * @generated from field: int64 amount_due = 6;
   */
  amountDue: bigint;

  /**
   * Amount paid in cents.
   *
   * @generated from field: int64 amount_paid = 7;
   */
  amountPaid: bigint;

  /**
   * ISO 4217 currency code, lowercase.
   *
   * @generated from field: string currency = 8;
   */
  currency: string;

  /**
   * Human-readable invoice number (provider-issued).
   *
   * @generated from field: string number = 9;
   */
  number: string;

  /**
   * URL for the provider-hosted invoice page.
   *
   * @generated from field: string hosted_invoice_url = 10;
   */
  hostedInvoiceUrl: string;

  /**
   * URL for the PDF version of the invoice.
   *
   * @generated from field: string invoice_pdf = 11;
   */
  invoicePdf: string;

  /**
   * When the invoice was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * When the invoice row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;

  /**
   * Chronological log of status transitions. The last entry always matches
   * `status`. Stored only inside the JSONB `data` blob — never promoted to
   * a column — because it's diagnostic history, not a query key.
   *
   * @generated from field: repeated modules.billing.proto.v1.Invoice.StatusChange status_history = 22;
   */
  statusHistory: Invoice_StatusChange[];
};

/**
 * A billing invoice.
 *
 * @generated from message modules.billing.proto.v1.Invoice
 */
export type InvoiceJson = {
  /**
   * Provider-issued invoice id.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.shared.proto.v1.BillingProvider provider = 2;
   */
  provider?: BillingProviderJson;

  /**
   * Supabase auth user id.
   *
   * @generated from field: string user_id = 3;
   */
  userId?: string;

  /**
   * Subscription the invoice belongs to (if any).
   *
   * @generated from field: string subscription_id = 4;
   */
  subscriptionId?: string;

  /**
   * Lifecycle status.
   *
   * @generated from field: modules.billing.proto.v1.Invoice.InvoiceStatus status = 5;
   */
  status?: Invoice_InvoiceStatusJson;

  /**
   * Amount due in cents.
   *
   * @generated from field: int64 amount_due = 6;
   */
  amountDue?: string;

  /**
   * Amount paid in cents.
   *
   * @generated from field: int64 amount_paid = 7;
   */
  amountPaid?: string;

  /**
   * ISO 4217 currency code, lowercase.
   *
   * @generated from field: string currency = 8;
   */
  currency?: string;

  /**
   * Human-readable invoice number (provider-issued).
   *
   * @generated from field: string number = 9;
   */
  number?: string;

  /**
   * URL for the provider-hosted invoice page.
   *
   * @generated from field: string hosted_invoice_url = 10;
   */
  hostedInvoiceUrl?: string;

  /**
   * URL for the PDF version of the invoice.
   *
   * @generated from field: string invoice_pdf = 11;
   */
  invoicePdf?: string;

  /**
   * When the invoice was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * When the invoice row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;

  /**
   * Chronological log of status transitions. The last entry always matches
   * `status`. Stored only inside the JSONB `data` blob — never promoted to
   * a column — because it's diagnostic history, not a query key.
   *
   * @generated from field: repeated modules.billing.proto.v1.Invoice.StatusChange status_history = 22;
   */
  statusHistory?: Invoice_StatusChangeJson[];
};

/**
 * Describes the message modules.billing.proto.v1.Invoice.
 * Use `create(InvoiceSchema)` to create a new message.
 */
export const InvoiceSchema: GenMessage<Invoice, {jsonType: InvoiceJson}> = /*@__PURE__*/
  messageDesc(file_modules_billing_proto_v1_invoice, 0);

/**
 * One entry in the status history log.
 *
 * @generated from message modules.billing.proto.v1.Invoice.StatusChange
 */
export type Invoice_StatusChange = Message<"modules.billing.proto.v1.Invoice.StatusChange"> & {
  /**
   * The status the invoice transitioned *to* at this point.
   *
   * @generated from field: modules.billing.proto.v1.Invoice.InvoiceStatus status = 1;
   */
  status: Invoice_InvoiceStatus;

  /**
   * When the transition happened.
   *
   * @generated from field: google.protobuf.Timestamp changed_at = 2;
   */
  changedAt?: Timestamp;
};

/**
 * One entry in the status history log.
 *
 * @generated from message modules.billing.proto.v1.Invoice.StatusChange
 */
export type Invoice_StatusChangeJson = {
  /**
   * The status the invoice transitioned *to* at this point.
   *
   * @generated from field: modules.billing.proto.v1.Invoice.InvoiceStatus status = 1;
   */
  status?: Invoice_InvoiceStatusJson;

  /**
   * When the transition happened.
   *
   * @generated from field: google.protobuf.Timestamp changed_at = 2;
   */
  changedAt?: TimestampJson;
};

/**
 * Describes the message modules.billing.proto.v1.Invoice.StatusChange.
 * Use `create(Invoice_StatusChangeSchema)` to create a new message.
 */
export const Invoice_StatusChangeSchema: GenMessage<Invoice_StatusChange, {jsonType: Invoice_StatusChangeJson}> = /*@__PURE__*/
  messageDesc(file_modules_billing_proto_v1_invoice, 0, 0);

/**
 * Lifecycle states of an Invoice.
 *
 * @generated from enum modules.billing.proto.v1.Invoice.InvoiceStatus
 */
export enum Invoice_InvoiceStatus {
  /**
   * The invoice is not specified.
   *
   * @generated from enum value: INVOICE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The invoice is a draft.
   *
   * @generated from enum value: INVOICE_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * The invoice is open.
   *
   * @generated from enum value: INVOICE_STATUS_OPEN = 2;
   */
  OPEN = 2,

  /**
   * The invoice is paid.
   *
   * @generated from enum value: INVOICE_STATUS_PAID = 3;
   */
  PAID = 3,

  /**
   * The invoice is uncollectible.
   *
   * @generated from enum value: INVOICE_STATUS_UNCOLLECTIBLE = 4;
   */
  UNCOLLECTIBLE = 4,

  /**
   * The invoice is void.
   *
   * @generated from enum value: INVOICE_STATUS_VOID = 5;
   */
  VOID = 5,
}

/**
 * Lifecycle states of an Invoice.
 *
 * @generated from enum modules.billing.proto.v1.Invoice.InvoiceStatus
 */
export type Invoice_InvoiceStatusJson = "INVOICE_STATUS_UNSPECIFIED" | "INVOICE_STATUS_DRAFT" | "INVOICE_STATUS_OPEN" | "INVOICE_STATUS_PAID" | "INVOICE_STATUS_UNCOLLECTIBLE" | "INVOICE_STATUS_VOID";

/**
 * Describes the enum modules.billing.proto.v1.Invoice.InvoiceStatus.
 */
export const Invoice_InvoiceStatusSchema: GenEnum<Invoice_InvoiceStatus, Invoice_InvoiceStatusJson> = /*@__PURE__*/
  enumDesc(file_modules_billing_proto_v1_invoice, 0, 0);

