// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/billing/proto/v1/price.proto (package modules.billing.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { BillingProvider, BillingProviderJson } from "../../../shared/proto/v1/billing-provider_pb";
import { file_modules_shared_proto_v1_billing_provider } from "../../../shared/proto/v1/billing-provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/billing/proto/v1/price.proto.
 */
export const file_modules_billing_proto_v1_price: GenFile = /*@__PURE__*/
  fileDesc("CiRtb2R1bGVzL2JpbGxpbmcvcHJvdG8vdjEvcHJpY2UucHJvdG8SGG1vZHVsZXMuYmlsbGluZy5wcm90by52MSLOAgoFUHJpY2USCgoCaWQYASABKAkSOwoIcHJvdmlkZXIYAiABKA4yKS5tb2R1bGVzLmJpbGxpbmcucHJvdG8udjEuQmlsbGluZ1Byb3ZpZGVyEhIKCnByb2R1Y3RfaWQYAyABKAkSDgoGYWN0aXZlGAQgASgIEhAKCGN1cnJlbmN5GAUgASgJEhgKC3VuaXRfYW1vdW50GAYgASgDSACIAQESFQoIaW50ZXJ2YWwYByABKAlIAYgBARIYChBhbGxvd2VkX3VzZXJfaWRzGAggAygJEi4KCmNyZWF0ZWRfYXQYFCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYFSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQg4KDF91bml0X2Ftb3VudEILCglfaW50ZXJ2YWxiBnByb3RvMw", [file_google_protobuf_timestamp, file_modules_shared_proto_v1_billing_provider]);

/**
 * A specific price point for a Product (e.g. monthly R$29).
 *
 * @generated from message modules.billing.proto.v1.Price
 */
export type Price = Message<"modules.billing.proto.v1.Price"> & {
  /**
   * Provider-issued price id.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.billing.proto.v1.BillingProvider provider = 2;
   */
  provider: BillingProvider;

  /**
   * Id of the owning Product.
   *
   * @generated from field: string product_id = 3;
   */
  productId: string;

  /**
   * Whether the price is currently for sale.
   *
   * @generated from field: bool active = 4;
   */
  active: boolean;

  /**
   * ISO 4217 currency code, lowercase (e.g. "brl").
   *
   * @generated from field: string currency = 5;
   */
  currency: string;

  /**
   * Unit amount in the smallest currency unit (cents). Null if not set.
   *
   * @generated from field: optional int64 unit_amount = 6;
   */
  unitAmount?: bigint;

  /**
   * Billing interval ("month", "year"). Null if not recurring.
   *
   * @generated from field: optional string interval = 7;
   */
  interval?: string;

  /**
   * Optional user allowlist. When empty, the price is public (anyone can see
   * and check out with it). When non-empty, only Supabase auth user ids in
   * this list are allowed to see the price or start a checkout against it —
   * used for one-off deals, comps, or private bundles. Enforced at the
   * application layer (listings + checkout), not in Stripe.
   *
   * @generated from field: repeated string allowed_user_ids = 8;
   */
  allowedUserIds: string[];

  /**
   * When the price row was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * When the price row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;
};

/**
 * A specific price point for a Product (e.g. monthly R$29).
 *
 * @generated from message modules.billing.proto.v1.Price
 */
export type PriceJson = {
  /**
   * Provider-issued price id.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.billing.proto.v1.BillingProvider provider = 2;
   */
  provider?: BillingProviderJson;

  /**
   * Id of the owning Product.
   *
   * @generated from field: string product_id = 3;
   */
  productId?: string;

  /**
   * Whether the price is currently for sale.
   *
   * @generated from field: bool active = 4;
   */
  active?: boolean;

  /**
   * ISO 4217 currency code, lowercase (e.g. "brl").
   *
   * @generated from field: string currency = 5;
   */
  currency?: string;

  /**
   * Unit amount in the smallest currency unit (cents). Null if not set.
   *
   * @generated from field: optional int64 unit_amount = 6;
   */
  unitAmount?: string;

  /**
   * Billing interval ("month", "year"). Null if not recurring.
   *
   * @generated from field: optional string interval = 7;
   */
  interval?: string;

  /**
   * Optional user allowlist. When empty, the price is public (anyone can see
   * and check out with it). When non-empty, only Supabase auth user ids in
   * this list are allowed to see the price or start a checkout against it —
   * used for one-off deals, comps, or private bundles. Enforced at the
   * application layer (listings + checkout), not in Stripe.
   *
   * @generated from field: repeated string allowed_user_ids = 8;
   */
  allowedUserIds?: string[];

  /**
   * When the price row was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * When the price row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;
};

/**
 * Describes the message modules.billing.proto.v1.Price.
 * Use `create(PriceSchema)` to create a new message.
 */
export const PriceSchema: GenMessage<Price, {jsonType: PriceJson}> = /*@__PURE__*/
  messageDesc(file_modules_billing_proto_v1_price, 0);

