// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/billing/proto/v1/product.proto (package modules.billing.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { BillingProvider, BillingProviderJson } from "../../../shared/proto/v1/billing-provider_pb";
import { file_modules_shared_proto_v1_billing_provider } from "../../../shared/proto/v1/billing-provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/billing/proto/v1/product.proto.
 */
export const file_modules_billing_proto_v1_product: GenFile = /*@__PURE__*/
  fileDesc("CiZtb2R1bGVzL2JpbGxpbmcvcHJvdG8vdjEvcHJvZHVjdC5wcm90bxIYbW9kdWxlcy5iaWxsaW5nLnByb3RvLnYxIusCCgdQcm9kdWN0EgoKAmlkGAEgASgJEjsKCHByb3ZpZGVyGAIgASgOMikubW9kdWxlcy5iaWxsaW5nLnByb3RvLnYxLkJpbGxpbmdQcm92aWRlchIOCgZhY3RpdmUYAyABKAgSDAoEbmFtZRgEIAEoCRITCgtkZXNjcmlwdGlvbhgFIAEoCRIQCghmZWF0dXJlcxgGIAMoCRJBCghtZXRhZGF0YRgHIAMoCzIvLm1vZHVsZXMuYmlsbGluZy5wcm90by52MS5Qcm9kdWN0Lk1ldGFkYXRhRW50cnkSLgoKY3JlYXRlZF9hdBgUIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgVIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAaLwoNTWV0YWRhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBYgZwcm90bzM", [file_google_protobuf_timestamp, file_modules_shared_proto_v1_billing_provider]);

/**
 * A sellable product in the payment provider's catalog.
 *
 * @generated from message modules.billing.proto.v1.Product
 */
export type Product = Message<"modules.billing.proto.v1.Product"> & {
  /**
   * Provider-issued product id.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.billing.proto.v1.BillingProvider provider = 2;
   */
  provider: BillingProvider;

  /**
   * Whether the product is currently for sale.
   *
   * @generated from field: bool active = 3;
   */
  active: boolean;

  /**
   * Display name.
   *
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * Display description (may be empty).
   *
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * Bullet-point features for the pricing card.
   *
   * @generated from field: repeated string features = 6;
   */
  features: string[];

  /**
   * Arbitrary provider metadata (e.g. tier_order, highlighted).
   *
   * @generated from field: map<string, string> metadata = 7;
   */
  metadata: { [key: string]: string };

  /**
   * When the product row was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * When the product row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;
};

/**
 * A sellable product in the payment provider's catalog.
 *
 * @generated from message modules.billing.proto.v1.Product
 */
export type ProductJson = {
  /**
   * Provider-issued product id.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.billing.proto.v1.BillingProvider provider = 2;
   */
  provider?: BillingProviderJson;

  /**
   * Whether the product is currently for sale.
   *
   * @generated from field: bool active = 3;
   */
  active?: boolean;

  /**
   * Display name.
   *
   * @generated from field: string name = 4;
   */
  name?: string;

  /**
   * Display description (may be empty).
   *
   * @generated from field: string description = 5;
   */
  description?: string;

  /**
   * Bullet-point features for the pricing card.
   *
   * @generated from field: repeated string features = 6;
   */
  features?: string[];

  /**
   * Arbitrary provider metadata (e.g. tier_order, highlighted).
   *
   * @generated from field: map<string, string> metadata = 7;
   */
  metadata?: { [key: string]: string };

  /**
   * When the product row was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * When the product row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;
};

/**
 * Describes the message modules.billing.proto.v1.Product.
 * Use `create(ProductSchema)` to create a new message.
 */
export const ProductSchema: GenMessage<Product, {jsonType: ProductJson}> = /*@__PURE__*/
  messageDesc(file_modules_billing_proto_v1_product, 0);

