// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file modules/billing/proto/v1/subscription.proto (package modules.billing.proto.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { BillingProvider, BillingProviderJson } from "../../../shared/proto/v1/billing_provider_pb";
import { file_modules_shared_proto_v1_billing_provider } from "../../../shared/proto/v1/billing_provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/billing/proto/v1/subscription.proto.
 */
export const file_modules_billing_proto_v1_subscription: GenFile = /*@__PURE__*/
  fileDesc("Cittb2R1bGVzL2JpbGxpbmcvcHJvdG8vdjEvc3Vic2NyaXB0aW9uLnByb3RvEhhtb2R1bGVzLmJpbGxpbmcucHJvdG8udjEi0QYKDFN1YnNjcmlwdGlvbhIKCgJpZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEjoKCHByb3ZpZGVyGAMgASgOMigubW9kdWxlcy5zaGFyZWQucHJvdG8udjEuQmlsbGluZ1Byb3ZpZGVyEhAKCHByaWNlX2lkGAQgASgJEkkKBnN0YXR1cxgFIAEoDjI5Lm1vZHVsZXMuYmlsbGluZy5wcm90by52MS5TdWJzY3JpcHRpb24uU3Vic2NyaXB0aW9uU3RhdHVzEjIKCXRyaWFsX2VuZBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAIgBARI7ChJjdXJyZW50X3BlcmlvZF9lbmQYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAGIAQESHAoUY2FuY2VsX2F0X3BlcmlvZF9lbmQYCCABKAgSLgoKY3JlYXRlZF9hdBgUIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgVIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASSwoOc3RhdHVzX2hpc3RvcnkYFiADKAsyMy5tb2R1bGVzLmJpbGxpbmcucHJvdG8udjEuU3Vic2NyaXB0aW9uLlN0YXR1c0NoYW5nZRqJAQoMU3RhdHVzQ2hhbmdlEkkKBnN0YXR1cxgBIAEoDjI5Lm1vZHVsZXMuYmlsbGluZy5wcm90by52MS5TdWJzY3JpcHRpb24uU3Vic2NyaXB0aW9uU3RhdHVzEi4KCmNoYW5nZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIp0BChJTdWJzY3JpcHRpb25TdGF0dXMSIwofU1VCU0NSSVBUSU9OX1NUQVRVU19VTlNQRUNJRklFRBAAEiAKHFNVQlNDUklQVElPTl9TVEFUVVNfVFJJQUxJTkcQARIeChpTVUJTQ1JJUFRJT05fU1RBVFVTX0FDVElWRRACEiAKHFNVQlNDUklQVElPTl9TVEFUVVNfSU5BQ1RJVkUQA0IMCgpfdHJpYWxfZW5kQhUKE19jdXJyZW50X3BlcmlvZF9lbmRiBnByb3RvMw", [file_google_protobuf_timestamp, file_modules_shared_proto_v1_billing_provider]);

/**
 * A user's recurring subscription.
 *
 * @generated from message modules.billing.proto.v1.Subscription
 */
export type Subscription = Message<"modules.billing.proto.v1.Subscription"> & {
  /**
   * Provider-issued subscription id.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Supabase auth user id.
   *
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.shared.proto.v1.BillingProvider provider = 3;
   */
  provider: BillingProvider;

  /**
   * Id of the Price the user is subscribed to.
   *
   * @generated from field: string price_id = 4;
   */
  priceId: string;

  /**
   * Current status. Domain-level lifecycle, independent of provider
   * vocabulary — the raw Stripe status is preserved inside `data` (JSONB).
   *
   * @generated from field: modules.billing.proto.v1.Subscription.SubscriptionStatus status = 5;
   */
  status: Subscription_SubscriptionStatus;

  /**
   * When the trial ends (if any).
   *
   * @generated from field: optional google.protobuf.Timestamp trial_end = 6;
   */
  trialEnd?: Timestamp;

  /**
   * End of the current billing period (if any).
   *
   * @generated from field: optional google.protobuf.Timestamp current_period_end = 7;
   */
  currentPeriodEnd?: Timestamp;

  /**
   * Whether the subscription will end at the current period end.
   *
   * @generated from field: bool cancel_at_period_end = 8;
   */
  cancelAtPeriodEnd: boolean;

  /**
   * When the subscription row was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * When the subscription row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;

  /**
   * Chronological log of status transitions. The last entry always matches
   * `status`. Stored only inside the JSONB `data` blob — never promoted to a
   * column — because it's diagnostic history, not a query key.
   *
   * @generated from field: repeated modules.billing.proto.v1.Subscription.StatusChange status_history = 22;
   */
  statusHistory: Subscription_StatusChange[];
};

/**
 * A user's recurring subscription.
 *
 * @generated from message modules.billing.proto.v1.Subscription
 */
export type SubscriptionJson = {
  /**
   * Provider-issued subscription id.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * Supabase auth user id.
   *
   * @generated from field: string user_id = 2;
   */
  userId?: string;

  /**
   * Payment provider.
   *
   * @generated from field: modules.shared.proto.v1.BillingProvider provider = 3;
   */
  provider?: BillingProviderJson;

  /**
   * Id of the Price the user is subscribed to.
   *
   * @generated from field: string price_id = 4;
   */
  priceId?: string;

  /**
   * Current status. Domain-level lifecycle, independent of provider
   * vocabulary — the raw Stripe status is preserved inside `data` (JSONB).
   *
   * @generated from field: modules.billing.proto.v1.Subscription.SubscriptionStatus status = 5;
   */
  status?: Subscription_SubscriptionStatusJson;

  /**
   * When the trial ends (if any).
   *
   * @generated from field: optional google.protobuf.Timestamp trial_end = 6;
   */
  trialEnd?: TimestampJson;

  /**
   * End of the current billing period (if any).
   *
   * @generated from field: optional google.protobuf.Timestamp current_period_end = 7;
   */
  currentPeriodEnd?: TimestampJson;

  /**
   * Whether the subscription will end at the current period end.
   *
   * @generated from field: bool cancel_at_period_end = 8;
   */
  cancelAtPeriodEnd?: boolean;

  /**
   * When the subscription row was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: TimestampJson;

  /**
   * When the subscription row was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: TimestampJson;

  /**
   * Chronological log of status transitions. The last entry always matches
   * `status`. Stored only inside the JSONB `data` blob — never promoted to a
   * column — because it's diagnostic history, not a query key.
   *
   * @generated from field: repeated modules.billing.proto.v1.Subscription.StatusChange status_history = 22;
   */
  statusHistory?: Subscription_StatusChangeJson[];
};

/**
 * Describes the message modules.billing.proto.v1.Subscription.
 * Use `create(SubscriptionSchema)` to create a new message.
 */
export const SubscriptionSchema: GenMessage<Subscription, {jsonType: SubscriptionJson}> = /*@__PURE__*/
  messageDesc(file_modules_billing_proto_v1_subscription, 0);

/**
 * One entry in the status history log.
 *
 * @generated from message modules.billing.proto.v1.Subscription.StatusChange
 */
export type Subscription_StatusChange = Message<"modules.billing.proto.v1.Subscription.StatusChange"> & {
  /**
   * The status the subscription transitioned *to* at this point.
   *
   * @generated from field: modules.billing.proto.v1.Subscription.SubscriptionStatus status = 1;
   */
  status: Subscription_SubscriptionStatus;

  /**
   * When the transition happened.
   *
   * @generated from field: google.protobuf.Timestamp changed_at = 2;
   */
  changedAt?: Timestamp;
};

/**
 * One entry in the status history log.
 *
 * @generated from message modules.billing.proto.v1.Subscription.StatusChange
 */
export type Subscription_StatusChangeJson = {
  /**
   * The status the subscription transitioned *to* at this point.
   *
   * @generated from field: modules.billing.proto.v1.Subscription.SubscriptionStatus status = 1;
   */
  status?: Subscription_SubscriptionStatusJson;

  /**
   * When the transition happened.
   *
   * @generated from field: google.protobuf.Timestamp changed_at = 2;
   */
  changedAt?: TimestampJson;
};

/**
 * Describes the message modules.billing.proto.v1.Subscription.StatusChange.
 * Use `create(Subscription_StatusChangeSchema)` to create a new message.
 */
export const Subscription_StatusChangeSchema: GenMessage<Subscription_StatusChange, {jsonType: Subscription_StatusChangeJson}> = /*@__PURE__*/
  messageDesc(file_modules_billing_proto_v1_subscription, 0, 0);

/**
 * Lifecycle states of a Subscription. Provider-agnostic: Stripe's
 * past_due / canceled / unpaid / incomplete / incomplete_expired / paused
 * all fold into ACTIVE (past_due with grace) or INACTIVE (terminal).
 *
 * @generated from enum modules.billing.proto.v1.Subscription.SubscriptionStatus
 */
export enum Subscription_SubscriptionStatus {
  /**
   * The status is not specified.
   *
   * @generated from enum value: SUBSCRIPTION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The subscription is in a trial period — access granted.
   *
   * @generated from enum value: SUBSCRIPTION_STATUS_TRIALING = 1;
   */
  TRIALING = 1,

  /**
   * The subscription is paid and in good standing — access granted.
   * Includes the grace period during a failed-payment retry window.
   *
   * @generated from enum value: SUBSCRIPTION_STATUS_ACTIVE = 2;
   */
  ACTIVE = 2,

  /**
   * The subscription has lapsed (canceled / dunning exhausted / trial
   * ended without payment). Row kept for audit; access dropped to free.
   *
   * @generated from enum value: SUBSCRIPTION_STATUS_INACTIVE = 3;
   */
  INACTIVE = 3,
}

/**
 * Lifecycle states of a Subscription. Provider-agnostic: Stripe's
 * past_due / canceled / unpaid / incomplete / incomplete_expired / paused
 * all fold into ACTIVE (past_due with grace) or INACTIVE (terminal).
 *
 * @generated from enum modules.billing.proto.v1.Subscription.SubscriptionStatus
 */
export type Subscription_SubscriptionStatusJson = "SUBSCRIPTION_STATUS_UNSPECIFIED" | "SUBSCRIPTION_STATUS_TRIALING" | "SUBSCRIPTION_STATUS_ACTIVE" | "SUBSCRIPTION_STATUS_INACTIVE";

/**
 * Describes the enum modules.billing.proto.v1.Subscription.SubscriptionStatus.
 */
export const Subscription_SubscriptionStatusSchema: GenEnum<Subscription_SubscriptionStatus, Subscription_SubscriptionStatusJson> = /*@__PURE__*/
  enumDesc(file_modules_billing_proto_v1_subscription, 0, 0);

